FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /app

COPY . .

RUN mvn -pl notification-service -am clean package -DskipTests

FROM eclipse-temurin:21-jdk
WORKDIR /app

COPY --from=build /app/notification-service/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]